version: '3.9'

services:
  service-order:
    build:
      dockerfile: service-order/Dockerfile
    volumes:
      - ./service-order/src/:/src
      - ./service-order/docs/oas.yaml:/docs/oas.yaml
    command: uvicorn web.app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - AUTH_ON=True
    tty: true
  service-kitchen:
    build:
      dockerfile: service-kitchen/Dockerfile
    volumes:
      - ./service-kitchen/src/:/src
      - ./service-kitchen/docs/oas.yaml:/docs/oas.yaml
    command: flask run --reload --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    tty: true
  service-products:
    build:
      dockerfile: service-products/Dockerfile
    volumes:
      - ./service-products/src/:/src
    command: uvicorn server:server --reload --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    tty: true
#  mock-service-kitchen:
#    build:
#      dockerfile: mock-service-kitchen/Dockerfile
#    volumes:
#      - ./mock-service-kitchen/src/:/src
#      - ./mock-service-kitchen/docs/kitchen.yaml:/docs/kitchen.yaml
#    command: ./node_modules/.bin/prism mock /docs/kitchen.yaml --host 0.0.0.0 --port 3000
#    ports:
#      - "3000:3000"
#    tty: true
#  mock-service-payments:
#    build:
#      dockerfile: mock-service-payments/Dockerfile
#    volumes:
#      - ./mock-service-payments/src/:/src
#      - ./mock-service-payments/docs/payments.yaml:/docs/payments.yaml
#    command: ./node_modules/.bin/prism mock /docs/payments.yaml --host 0.0.0.0 --port 3001
#    ports:
#      - "3001:3001"
#    tty: true
#  mock-graphql-server:
#    build:
#      dockerfile: mock-graphql-server/Dockerfile
#    volumes:
#      - ./mock-graphql-server/src/:/src
#    #command: ./node_modules/.bin/graphql-faker schema.graphql --host 0.0.0.0 --port 3001
#    #ports:
#    #  - "9002:9002"
#    tty: true