[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Masaru Fukazawa"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.2.1"
schemathesis = "^3.29.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
